CREATE TABLE [dbo].[Client] (
    [Id]                               INT           IDENTITY (1, 1) NOT NULL,
    [Name]                             NVARCHAR (50) NOT NULL,
    [Address]                          NVARCHAR (50) NULL,
    [BusinessPhoneExtension]           TEXT          NULL,
    [BusinessPhone]                    TEXT          NULL,
    [FaxNumber]                        TEXT          NULL,
    [Email]                            TEXT          NULL,
    [IsActive]                         BIT           NULL,
    [LicenseNumber]                    NVARCHAR (50) NULL,
    [Website]                          NVARCHAR (50) NULL,
    [AbbreviatedName]                  NVARCHAR (50) NULL,
    [IsVendor]                         BIT           NULL,
    [ClientLogo]                       IMAGE         NULL,
    [ClientRegistrationNumber]         NVARCHAR (50) NULL,
    [ClientType]                       INT           NULL,
    [BondWebsite]                      NVARCHAR (50) NULL,
    [TermsAndConditions]               TEXT          NULL,
    [IsTermsAndConditionsEnabled]      BIT           CONSTRAINT [DF_Client_IsTermsAndConditionsEnabled] DEFAULT ((0)) NULL,
    [IsTriggerReacceptanceForAllUsers] BIT           NULL,
    [PrimaryContactUserId]             INT           CONSTRAINT [DF_Client_PrimaryContactUserId] DEFAULT ((0)) NULL,
    [LaborUnionName]                   NVARCHAR (50) NULL,
    [City]                             NVARCHAR (50) NULL,
    [State]                            NVARCHAR (50) NULL,
    [Zip]                              NVARCHAR (50) NULL,
    [ContractSignerUserId]             INT           NULL,
    [CreatedDate]                      DATETIME      NULL,
    [CreatedByUserId]                  INT           NULL,
    [IsDeleted]                        BIT           CONSTRAINT [DF_Client_IsDeleted] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED ([Id] ASC)
);

