CREATE TABLE [dbo].[Users] (
    [Id]                 INT           IDENTITY (1, 1) NOT NULL,
    [FirstName]          NVARCHAR (50) NOT NULL,
    [LastName]           NVARCHAR (50) NOT NULL,
    [Email]              NVARCHAR (50) NOT NULL,
    [BusinessPhoneExt]   NVARCHAR (50) NULL,
    [BusinessPhone]      NVARCHAR (50) NULL,
    [MobilePhone]        NVARCHAR (50) NULL,
    [Password]           TEXT          NULL,
    [IsGlobalAdmin]      BIT           CONSTRAINT [DF_Users_IsGlobalAdmin] DEFAULT ((0)) NULL,
    [JobTitle]           NVARCHAR (50) NULL,
    [Address]            NVARCHAR (50) NULL,
    [IsActive]           BIT           CONSTRAINT [DF_Users_IsActive] DEFAULT ((1)) NULL,
    [IsEmployeeOfClient] BIT           CONSTRAINT [DF_Users_IsEmployee] DEFAULT ((0)) NULL,
    [EmployeeNumber]     NVARCHAR (50) NULL,
    [ClientId]           INT           NULL,
    [UserRoleId]         INT           NULL,
    [Salt]               TEXT          NULL,
    [IsInsuranceManger]  INT           CONSTRAINT [DF_Users_IsInsuranceManger] DEFAULT ((0)) NULL,
    [City]               NVARCHAR (50) NULL,
    [State]              NVARCHAR (50) CONSTRAINT [DF_Users_StateId] DEFAULT ((1)) NULL,
    [Zip]                NVARCHAR (50) NULL,
    [IsConractSigner]    BIT           CONSTRAINT [DF_Users_IsConractSigner] DEFAULT ((0)) NULL,
    [IsInvoiceSigner]    BIT           CONSTRAINT [DF_Users_IsInvoiceSigner] DEFAULT ((0)) NULL,
    [CreatedDate]        DATETIME      NULL,
    [CreatedByUserId]    INT           NULL,
    [IsDeleted]          BIT           CONSTRAINT [DF_Users_IsDeleted] DEFAULT ((0)) NULL,
    [Notes]              TEXT          NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC)
);

